// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type ConvertRequest struct {
	LongUrl string `json:"longUrl" validate:"required,url"`
}

type ConvertResponse struct {
	ShortUrl string `json:"shortUrl"`
}
