// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: convert.proto

package convertclient

import (
	"context"

	"shortenLink/cmd/convert-rpc/shortenLink/rpc/convert"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ConvertRequest  = convert.ConvertRequest
	ConvertResponse = convert.ConvertResponse

	Convert interface {
		Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error)
	}

	defaultConvert struct {
		cli zrpc.Client
	}
)

func NewConvert(cli zrpc.Client) Convert {
	return &defaultConvert{
		cli: cli,
	}
}

func (m *defaultConvert) Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertResponse, error) {
	client := convert.NewConvertClient(m.cli.Conn())
	return client.Convert(ctx, in, opts...)
}
