// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: show.proto

package server

import (
	"context"

	"shortenLink/cmd/show-rpc/internal/logic"
	"shortenLink/cmd/show-rpc/internal/svc"
	"shortenLink/cmd/show-rpc/shortenLink/rpc/show"
)

type ShowServer struct {
	svcCtx *svc.ServiceContext
	show.UnimplementedShowServer
}

func NewShowServer(svcCtx *svc.ServiceContext) *ShowServer {
	return &ShowServer{
		svcCtx: svcCtx,
	}
}

func (s *ShowServer) Show(ctx context.Context, in *show.ShowRequest) (*show.ShowResponse, error) {
	l := logic.NewShowLogic(ctx, s.svcCtx)
	return l.Show(in)
}
