// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: sequence.proto

package server

import (
	"context"

	"shortenLink/cmd/sequence-rpc/internal/logic"
	"shortenLink/cmd/sequence-rpc/internal/svc"
	"shortenLink/cmd/sequence-rpc/shortenLink/rpc/sequence"
)

type SequenceServer struct {
	svcCtx *svc.ServiceContext
	sequence.UnimplementedSequenceServer
}

func NewSequenceServer(svcCtx *svc.ServiceContext) *SequenceServer {
	return &SequenceServer{
		svcCtx: svcCtx,
	}
}

func (s *SequenceServer) Next(ctx context.Context, in *sequence.Empty) (*sequence.NextResp, error) {
	l := logic.NewNextLogic(ctx, s.svcCtx)
	return l.Next(in)
}
