// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: convert.proto

package server

import (
	"context"

	"shortenLink/cmd/convert-rpc/internal/logic"
	"shortenLink/cmd/convert-rpc/internal/svc"
	"shortenLink/cmd/convert-rpc/shortenLink/rpc/convert"
)

type ConvertServer struct {
	svcCtx *svc.ServiceContext
	convert.UnimplementedConvertServer
}

func NewConvertServer(svcCtx *svc.ServiceContext) *ConvertServer {
	return &ConvertServer{
		svcCtx: svcCtx,
	}
}

func (s *ConvertServer) Convert(ctx context.Context, in *convert.ConvertRequest) (*convert.ConvertResponse, error) {
	l := logic.NewConvertLogic(ctx, s.svcCtx)
	return l.Convert(in)
}
