// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: show.proto

package showclient

import (
	"context"

	"shortenLink/cmd/show-rpc/shortenLink/rpc/show"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ShowRequest  = show.ShowRequest
	ShowResponse = show.ShowResponse

	Show interface {
		Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowResponse, error)
	}

	defaultShow struct {
		cli zrpc.Client
	}
)

func NewShow(cli zrpc.Client) Show {
	return &defaultShow{
		cli: cli,
	}
}

func (m *defaultShow) Show(ctx context.Context, in *ShowRequest, opts ...grpc.CallOption) (*ShowResponse, error) {
	client := show.NewShowClient(m.cli.Conn())
	return client.Show(ctx, in, opts...)
}
