// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type ShowRequest struct {
	ShortUrl string `path:"shortUrl" validate:"required"`
}

type ShowResponse struct {
	LongUrl string `json:"longUrl"`
}
