// rpc/sequence/sequence.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: rpc/sequence/sequence.proto

package sequence

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sequence_sequence_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sequence_sequence_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rpc_sequence_sequence_proto_rawDescGZIP(), []int{0}
}

type NextResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NextResp) Reset() {
	*x = NextResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_sequence_sequence_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NextResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextResp) ProtoMessage() {}

func (x *NextResp) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_sequence_sequence_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextResp.ProtoReflect.Descriptor instead.
func (*NextResp) Descriptor() ([]byte, []int) {
	return file_rpc_sequence_sequence_proto_rawDescGZIP(), []int{1}
}

func (x *NextResp) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_rpc_sequence_sequence_proto protoreflect.FileDescriptor

var file_rpc_sequence_sequence_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x20, 0x0a, 0x08, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x32, 0x37, 0x0a, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x2b,
	0x0a, 0x04, 0x4e, 0x65, 0x78, 0x74, 0x12, 0x0f, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x12, 0x2e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x2e, 0x4e, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x42, 0x1a, 0x5a, 0x18, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x4c, 0x69, 0x6e, 0x6b, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73,
	0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_sequence_sequence_proto_rawDescOnce sync.Once
	file_rpc_sequence_sequence_proto_rawDescData = file_rpc_sequence_sequence_proto_rawDesc
)

func file_rpc_sequence_sequence_proto_rawDescGZIP() []byte {
	file_rpc_sequence_sequence_proto_rawDescOnce.Do(func() {
		file_rpc_sequence_sequence_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_sequence_sequence_proto_rawDescData)
	})
	return file_rpc_sequence_sequence_proto_rawDescData
}

var file_rpc_sequence_sequence_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_sequence_sequence_proto_goTypes = []interface{}{
	(*Empty)(nil),    // 0: sequence.Empty
	(*NextResp)(nil), // 1: sequence.NextResp
}
var file_rpc_sequence_sequence_proto_depIdxs = []int32{
	0, // 0: sequence.Sequence.Next:input_type -> sequence.Empty
	1, // 1: sequence.Sequence.Next:output_type -> sequence.NextResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_sequence_sequence_proto_init() }
func file_rpc_sequence_sequence_proto_init() {
	if File_rpc_sequence_sequence_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_sequence_sequence_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_sequence_sequence_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NextResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_sequence_sequence_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_sequence_sequence_proto_goTypes,
		DependencyIndexes: file_rpc_sequence_sequence_proto_depIdxs,
		MessageInfos:      file_rpc_sequence_sequence_proto_msgTypes,
	}.Build()
	File_rpc_sequence_sequence_proto = out.File
	file_rpc_sequence_sequence_proto_rawDesc = nil
	file_rpc_sequence_sequence_proto_goTypes = nil
	file_rpc_sequence_sequence_proto_depIdxs = nil
}
