filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - /var/log/nginx/shortener.access.log
    parsers:
      - ndjson:
          keys_under_root: true
          add_error_key: true
          overwrite_keys: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "nginx-access-%{+yyyy.MM.dd}"

setup.ilm.enabled: false
setup.template.enabled: false