// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"

	"shortenLink/cmd/show-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 根据短链 ShortUrl 跳转到长链
				Method:  http.MethodGet,
				Path:    "/:shortUrl",
				Handler: ShowHandler(serverCtx),
			},
		},
	)
}
